- id: black
  name: black (via docker)
  entry: black --py36 -S
  language: docker
  files: \.py$

- id: isort
  name: isort (via docker)
  entry: isort --recursive --apply
  language: docker
  files: \.py$
